# NumPy

### NumPy Arrays

In [1]:
my_list=[1,2,3]

import numpy as np

arr=np.array(my_list)

In [2]:
arr

array([1, 2, 3])

In [3]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
range(0,10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
np.arange(0,10,2) # with step size=2

array([0, 2, 4, 6, 8])

In [8]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [10]:
np.zeros((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [11]:
np.ones((3,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [12]:
np.linspace(0,5,10) #ten evenly split from 0 to 5

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [13]:
np.linspace(1,10,5) #5 evenly split from 1 to 10

array([  1.  ,   3.25,   5.5 ,   7.75,  10.  ])

In [14]:
np.linspace(0,10,5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [15]:
np.eye(4) #diagonal matrix

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [17]:
np.random.rand(3) #random numbers uniform

array([ 0.38978623,  0.9660041 ,  0.91038287])

In [18]:
np.random.rand(5,4)

array([[ 0.61528073,  0.32812355,  0.58246498,  0.86069224],
       [ 0.28789881,  0.37360924,  0.53380792,  0.13458953],
       [ 0.55788341,  0.31421946,  0.55407527,  0.49522858],
       [ 0.12299555,  0.65946846,  0.21499896,  0.24143066],
       [ 0.25628819,  0.36376404,  0.47844627,  0.24810562]])

In [19]:
np.random.randn(5) ##standard normal

array([-1.09479772, -0.76893155,  1.15388219, -0.66799706,  0.48006796])

In [21]:
np.random.randn(4,3)

array([[ 0.18660233,  0.79319579,  0.72718811],
       [-0.38124129, -0.59759249,  0.41603254],
       [ 0.86188119, -1.06736473, -1.27575489],
       [ 1.4841276 , -0.22063747,  0.90918557]])

In [23]:
np.random.randint(1,100) #low hign random integer between 1,99

33

In [24]:
np.random.randint(1,100,10)

array([54, 93, 55, 89,  3, 59, 98, 56, 17, 38])

In [25]:
arr=np.arange(25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr=np.random.randint(0,50,10)

In [29]:
ranarr

array([26, 21, 22, 29, 11,  2,  0, 38, 41,  8])

In [30]:
#how to reshape the array

arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
ranarr.max()

41

In [33]:
ranarr.min()

0

In [35]:
# if i want the location of the max value
ranarr.argmax()

8

In [37]:
ranarr.reshape(5,2).argmax()

8

In [38]:
ranarr.argmin()

6

In [39]:
arr.shape

(25L,)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
test=arr.reshape(5,5)

In [45]:
test.shape

(5L, 5L)

In [46]:
test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr.dtype #get the type

dtype('int32')

In [48]:
from numpy.random import randint

randint(2,10) #in case we are lazy to write "np.random.randint(2,10)"

6

### Numpy Array Indexing

In [49]:
import numpy as np

arr=np.arange(0,11)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr[8]

8

In [52]:
arr[2:5]

array([2, 3, 4])

In [53]:
arr[:6]  #everything up to index 6 (expluding)

array([0, 1, 2, 3, 4, 5])

In [54]:
arr[5:] #everything from 5th index

array([ 5,  6,  7,  8,  9, 10])

In [55]:
arr[0:5]=100

In [56]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [57]:
arr=np.arange(0,11)
slice_of_arr=arr[0:6]

In [58]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [59]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [60]:
slice_of_arr[:]=99

In [61]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [62]:
arr #!!!!! it changes also the original array!!!!

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [64]:
#in order to avoid this you should use the copy command

arr_copy=arr.copy()

In [66]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [69]:
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [70]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [71]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [72]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [74]:
# pick the (1,1) element "double bracket notation"

arr_2d[0][0]

5

In [76]:
# pick the first line
arr_2d[0]

array([ 5, 10, 15])

In [77]:
# single bracket notation

arr_2d[1,2]

30

In [78]:
arr_2d[1][2]

30

In [79]:
arr_2d[:2, 1:] # everything from rows 1,2 and from column 2 and everything

array([[10, 15],
       [25, 30]])

In [80]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [81]:
arr=np.arange(1,11)

In [85]:
bool_arr=arr>5

In [86]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [87]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [88]:
arr[arr<3]

array([1, 2])

arr_2d[arr_2d>10]

### NumPy Operations
- Array with Array
- Array with Scalars
- Universal Array Functions

In [96]:
arr=np.arange(0,11)

In [97]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [99]:
arr+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [100]:
arr*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [101]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [102]:
arr/arr # it returns 0 although 0/0 is not defined

C:\Users\gpipis\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in divide
  if __name__ == '__main__':


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [104]:
1.0/arr

C:\Users\gpipis\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in divide
  if __name__ == '__main__':


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [105]:
arr**2 #to the power of 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [106]:
np.sqrt(arr) #get the sqrt

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [107]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [108]:
np.max(arr)

10

In [109]:
arr.max() #alternative way

10

In [110]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

### Exercises

In [111]:
#create an array of 10 fives

np.ones(10)*5

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [113]:
np.zeros(10)+5

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [114]:
# create an array of the integers from 10 to 50

np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [115]:
# create an array of the EVEN integers from 10 to 50
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [116]:
# CREATE A 3X3 matrix with values ranging from 0 to 8

np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [117]:
# create a 3x3 identity matrix
np.eye(3,3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [118]:
# create random number between 0,1
np.random.rand(1)

array([ 0.57781659])

In [119]:
#use NUmPy to generate an array of 25 random numbers from norm dist
np.random.randn(25)

array([-0.57496356,  0.6398493 ,  1.29463451, -0.00229524, -0.23176276,
       -1.30571231,  0.03133629,  0.91235313,  0.20187731,  0.91403161,
        0.66490292,  0.90260197,  1.60342358, -0.21302501, -0.56204856,
        0.31790429, -0.14064887,  0.29176254, -2.22800712, -1.41100813,
        0.02924191, -1.15736477,  1.29339082, -1.03343874, -0.25873219])

In [120]:
np.random.randn(25).shape

(25L,)

In [124]:
# create an array from 0 to 1 with step 0.1
np.arange(1,101).reshape(10,10)/100.0

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [126]:
#alternative
np.linspace(0.01,1, 100).reshape(10,10)

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [127]:
mat=np.arange(1,26).reshape(5,5)

In [128]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [130]:
mat[2: , 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [140]:
mat[3,4] #get the 20

20

In [141]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [142]:
mat[:3,1]

array([ 2,  7, 12])

In [143]:
mat[-1,:]

array([21, 22, 23, 24, 25])

In [144]:
mat.sum()

325

In [146]:
mat.std()

7.2111025509279782

In [148]:
#get the col sums
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [149]:
#get the row sums
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])