# SciPy
SciPy is a collection of mathematical algorithms and convenience functions built on the Numpy extension of Python. It adds significant power to the interactive Python session by providing the user with high-level commands and classes for manipulating and visualizing data. With SciPy an interactive Python session becomes a data-processing and system-prototyping environment rivaling systems such as MATLAB, IDL, Octave, R-Lab, and SciLab.
The additional benefit of basing SciPy on Python is that this also makes a powerful programming language available for use in developing sophisticated programs and specialized applications. Scientific applications using SciPy benefit from the development of additional modules in numerous niches of the software landscape by developers across the world.
Everything from parallel programming to web and data-base subroutines and classes have been made available to the Python programmer. All of this power is available in addition to the mathematical libraries in SciPy.
We'll focus a lot more on NumPy arrays, but let's show some of the capabilities of SciPy:


In [1]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,8]])

In [2]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

### Linear Algebra
linalg

In [3]:
from scipy import linalg

In [4]:
# Compute the determinant of a matrix
linalg.det(A)

2.999999999999997

Compute pivoted LU decomposition of a matrix.
The decomposition is:  

A = P L U  

where P is a permutation matrix, L lower triangular with unit diagonal elements, and U upper triangular.

In [5]:
P, L, U = linalg.lu(A)

In [6]:
P

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]])

In [7]:
L

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.14285714,  1.        ,  0.        ],
       [ 0.57142857,  0.5       ,  1.        ]])

In [8]:
U

array([[ 7.        ,  8.        ,  8.        ],
       [ 0.        ,  0.85714286,  1.85714286],
       [ 0.        ,  0.        ,  0.5       ]])

In [9]:
np.dot(L,U)

array([[ 7.,  8.,  8.],
       [ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [10]:
# We can find out the eigenvalues and eigenvectors of this matrix:
EW, EV = linalg.eig(A)

In [11]:
EW

array([ 15.55528261+0.j,  -1.41940876+0.j,  -0.13587385+0.j])

In [12]:
EV

array([[-0.24043423, -0.67468642,  0.51853459],
       [-0.54694322, -0.23391616, -0.78895962],
       [-0.80190056,  0.70005819,  0.32964312]])

In [13]:
# Solving systems of linear equations can also be done:
v = np.array([[2],[3],[5]])

In [14]:
v

array([[2],
       [3],
       [5]])

In [15]:
s = linalg.solve(A,v)

In [16]:
s

array([[-2.33333333],
       [ 3.66666667],
       [-1.        ]])

## Sparse Linear Algebra

SciPy has some routines for computing with sparse and potentially very large matrices. The necessary tools are in the submodule scipy.sparse.  
We make one example on how to construct a large matrix:


In [22]:
from scipy import sparse

In [23]:
# Row-based linked list sparse matrix
A = sparse.lil_matrix((1000, 1000))

In [24]:
A

<1000x1000 sparse matrix of type '<type 'numpy.float64'>'
	with 0 stored elements in LInked List format>

In [25]:
A[0,:100] = np.random.rand(100)

In [28]:
A[1,100:200] = A[0,:100]

In [30]:
A.setdiag(np.random.rand(1000))

In [32]:
A

<1000x1000 sparse matrix of type '<type 'numpy.float64'>'
	with 1199 stored elements in LInked List format>

In [33]:
from scipy.sparse import linalg

In [34]:
# Convert this matrix to Compressed Sparse Row format.
A.tocsr()

<1000x1000 sparse matrix of type '<type 'numpy.float64'>'
	with 1199 stored elements in Compressed Sparse Row format>

In [35]:
A = A.tocsr()

In [36]:
b = np.random.rand(1000)

In [37]:
linalg.spsolve(A, b)

array([  6.63594181e+02,  -2.03882006e+02,   1.51482243e+01,
         1.05899742e+00,   2.41476910e-01,   1.30461930e+00,
         3.50441054e-01,   1.95853234e+00,   2.25846924e+00,
         1.85449823e+00,   1.20686690e+00,   8.31084977e-01,
         6.61213046e+00,   7.71139434e+00,   5.38900252e+00,
         2.10090233e-01,   3.32704333e+00,   2.01303092e+00,
         1.38258379e+00,   5.90877287e-01,   8.06821470e-01,
         1.58228508e+00,   8.00274349e+00,   6.06931718e+00,
         7.86026257e-01,   4.29524224e+00,   6.66118053e-01,
         1.08082079e+00,   4.00703834e-01,   5.83922310e-01,
         1.90660359e+00,   1.48346670e+00,   3.62732116e-01,
         1.30960376e+01,   1.83721270e+00,   9.59516129e-01,
         1.11938391e+00,   3.01681551e+00,   1.01658151e+00,
         6.75666020e-01,   1.17784539e+00,   1.71480053e-02,
         3.18857110e-01,   5.32209707e-01,   1.16189516e+00,
         3.50162311e-02,   4.71976263e+00,   1.65944836e+00,
         7.48399601e-02,